version: '3.8'
services:
  mongodb:
    container_name: mongo_db
    image: 'mongo'
    volumes:
      - 'data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: secret
    # env_file:
    #     - ./env/mongo.env
  backend:
    container_name: backend_container
    #context: .
    build: ./backend
    # build:
    #   context: .
    #   dockerfile: backend/Dockerfile
    ports:
      - '3001:80'
    volumes:
      - 'logs:/app/logs'
      - './backend:/app' #bind
      - '/app/node_modules'
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: secret
    # env_file:
    #   - ./env/backend.env

    depends_on:
      - mongodb

  frontend:
    container_name: frontend_container
    build: ./frontend
    ports:
      - '3000:3000'

    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true

    depends_on:
      - backend

volumes:
  data:
  logs: